### ISSUE TITLE
Gestion des documents attachés

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-suivi-perso#11]
Pouvoir attacher des documents à un message.
- Soit de son cartable
- Soit depuis son disque dur.

**Comment by heleroy** [comment]
La fenêtre qui permet de parcourir son ordinateur ou son cartable s’affiche très mal et, de plus, ne permet pas de rechercher dans son cartable, contrairement à ce que suggère l’infobulle...
D'ailleurs, l'idéal serait de modifier le texte de l'info bulle et de mettre plutôt "insérer un fichier de l'ordinateur ou de son cartable" ... plutôt que "ou non"
