### ISSUE TITLE
Garder ou pas l'avatar ?

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-suivi-perso#14]
certains collèges ne souhaitent pas conserver l'avatar de l'auteur des messages, car ce n'est pas dans leurs pratiques pédagogiques.
D'autres pensent le contraire. 

La gestion d'un paramètre d'application pourrait être envisagée.

**Comment by heleroy** [comment]
A l'heure actuelle, lors d'une publication sur le Suivi perso, l'avatar apparait, puis disparait après avoir actualisé le carnet (F5).
