### ISSUE TITLE
Gestion des droits - listing personnes à ajouter ne s'affiche pas

### ISSUE THREAD

**Issue by HuguesGithub** [laclasse-com/service-suivi-perso#40]
Sur l'écran de gestion des droits d'un élève, le listing des personnes pouvant être ajouté ne s'affiche pas.
L'erreur ne semble pas systématique (du moins elle survient majoritairement, mais il arrive que ça fonctionne).

L'url ciblée s'appuye sur le format suivant : http://localhost:9292/suivi/api/annuaire/etablissements/0693975W/personnels?uid_elv=VAE67621
On a en retour une erreur 500.

L'erreur survient par exemple pour Quentin DUPONT établissement Simone Weil pour l'utilisateur erasme

**Comment by HuguesGithub** [comment]
Lors de la génération du listing, si une des personnes était administrateur Technique, la boucle retournait un élément nil qui provoquait le plantage.
Ajout d'un contrôle pour éviter de retourner l'élément nil.

**Comment by TestsCGI** [comment]
Sur l'établissement Bac à Sable (environnement de production), l'erreur est systématique : impossible d'ajouter une personne au carnet : aucun listing n'est généré suite à la saisie du nom d'un utilisateur
