### ISSUE TITLE
Fonctionnement des contacts et de l'envoi de mail

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-suivi-perso#45]
Dans le carnet de suivi d'un élève sont répertoriés des contacts famille et des contacts collège.
Sur quels critères est constituée la liste des contacts collège ?
Les contacts famille et collège sont précédés d'une case à cocher permettant a priori de sélectionner les destinataires du mail à envoyer.
Une fois les destinataires sélectionnés, où rédige-t-on le mail et comment l'envoie-t-on ?

**Comment by heleroy** [comment]
Une fenêtre permet de rédiger le message par mail mais le bouton pour ajouter un fichier en donne aucune action. De plus, permettre de cocher une case pour envoyer une copie du mail aussi à l'expéditeur.

**Comment by heleroy** [comment]
L'ajout de nouvelles personnes n'a aucune action... comment et qui ajouter comme personne ?
