### ISSUE TITLE
Test V3 - 2016 : Rédaction et publication d'un message dans un onglet d'un carnet de suivi

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-suivi-perso#49]
Lors de la rédaction d'un message, la taille de la fenêtre de publication ne s'adapte pas à la taille du message en cours de rédaction. La barre d'outil permettant de mettre en forme et d'enrichir le texte reste positionnée au même endroit quelle que soit la taille du message.
Par ailleurs, lorsqu'une pièce jointe est ajoutée au message, la fenêtre Parcourir est superposée à la première fenêtre d'insertion de fichier et, elle reste affichée une fois le choix du fichier fait si bien que le bouton valider est en partie caché derrière. 
Lors de la publication d'un message avec PJ, 2 messages s'affichent :
- le message de confirmation de la publication :"votre message a été publié avec succès ..."
- un message d'erreur : "server error"
  Le message n'est en fait pas publié et la PJ continue d'apparaître sur la zone de publication lorsqu'on change d'onglet

**Comment by heleroy** [comment]
![serveur error](https://cloud.githubusercontent.com/assets/7963908/21104105/8fc2eabc-c085-11e6-847b-fd1a55e7fb31.png)

**Comment by heleroy** [comment]
Quand on publie son texte (sans doc joint=) ça fonctionne. Par contre, l'avatar de l'auteur apparaît mais disparaît après rechargement de la page.
De même l'heure de publication apparaît mais disparaît dès le rechargement de la page : elle revient à 1:00 à chaque rechargement.

**Comment by heleroy** [comment]
avant
![capture du 2016-12-12 16-14-53](https://cloud.githubusercontent.com/assets/7963908/21104331/6b9886e6-c086-11e6-87a3-f94853407343.png)
après rechargement (modif de l'avatar, de l'heure de publication, et multiplication par 6 de la publication...)
![capture du 2016-12-12 16-16-03](https://cloud.githubusercontent.com/assets/7963908/21104310/5a3e7e64-c086-11e6-8974-fbf043895093.png)
