### ISSUE TITLE
Accéder plus facilement aux carnets que l'on a créés ou sur lesquels on a des accès

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-suivi-perso#59]
Via une roue dentée dès le début de l'appli, un peu comme sur l'outil "publipostage" pour retrouver ses publipostages. Sinon, pour l'instant, il faut faire la procédure comme si on voulait créer un carnet... donc c'est long... et peu logique.

**Comment by cycojesus** [comment]
Afficher à l'utilisateur connecté les carnets le concernant. L'information est disponible dans la table :droits_specifiques

UI à définir
