### ISSUE TITLE
Affichage des accents non géré en lecture seule

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-suivi-perso#75]
Dans les onglets

Compte Alaloy elève Test 
![capture](https://user-images.githubusercontent.com/24314392/30050968-9c8117c0-9220-11e7-9634-9e17100db55e.PNG)

**Comment by gwenhael-le-moine** [comment]
effet de bord d'une conversion de base de données faites vendredi dernier.
