### ISSUE TITLE
Amélioration - prévoir la possibilité d'éditer sans avoir les droits de configuration d'onglet

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-suivi-perso#81]
PAr exemple : un élève ou parent devrait pouvoir éditer l'onglet et écrire des choses, mais ne pas changer les données de configuration. 

Ou bien seul l'administrateur/Créateur de l'onglet peut avoir les droits de configuration??

**Comment by gwenhael-le-moine** [comment]
- ajout d'un droit d'administration
