### ISSUE TITLE
bug - les onglets créés par les élèves sont visibles de tous malgré la gestion des droits par l'élève..

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-suivi-perso#84]
Peut être peut on laisser la possibilité aux élèves de créer des onglets libres (pour collaborer avec d'autres élèves), sans intervention des autres adultes ? 
Par défaut, l'administrateur ENT peut avoir accès en visibilité et en modification pour alerter, mais pas les profs et les parents. 

D'autant plus que cela peut faire beaucoup de groupes à gérer pour les profs.

**Comment by gwenhael-le-moine** [comment]
Un onglet est visible par :
- les utilisateurs ayant des droits dessus (par utilisateur ou profil (ou à terme partage public)),
- les admins d'établissement,
- les super-admins.

On pourrait rendre invisible aux admins/super-admins les onglets d'élèves strictement individuels. À discuter...

**Comment by gwenhael-le-moine** [comment]
Les onglets où l'élève est seul à avoir un droit sont invisibles même aux (super-)admin.
