### ISSUE TITLE
Amélioration affichage des images trop grandes

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-suivi-perso#85]
Pour les images copiées glissées, elles ne sont pas retaillées : dans le champ d'édition

![images importee](https://user-images.githubusercontent.com/24314392/30327779-9404daac-97cd-11e7-8e74-66994e950374.PNG)

**Comment by gwenhael-le-moine** [comment]
Le composant textangular fourni des outils de redimensionnement.
Laissons l'utilisateur faire.
